// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// relative_diff
arma::sp_mat relative_diff(arma::sp_mat& M);
RcppExport SEXP _mclink_relative_diff(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(relative_diff(M));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_relative_diff
arma::sp_mat shuffle_relative_diff(arma::sp_mat& M);
RcppExport SEXP _mclink_shuffle_relative_diff(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_relative_diff(M));
    return rcpp_result_gen;
END_RCPP
}
// cal_var
double cal_var(arma::sp_mat& M);
RcppExport SEXP _mclink_cal_var(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(cal_var(M));
    return rcpp_result_gen;
END_RCPP
}
// nonzero
arma::vec nonzero(arma::sp_mat& M);
RcppExport SEXP _mclink_nonzero(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(nonzero(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mclink_relative_diff", (DL_FUNC) &_mclink_relative_diff, 1},
    {"_mclink_shuffle_relative_diff", (DL_FUNC) &_mclink_shuffle_relative_diff, 1},
    {"_mclink_cal_var", (DL_FUNC) &_mclink_cal_var, 1},
    {"_mclink_nonzero", (DL_FUNC) &_mclink_nonzero, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mclink(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
