# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.mc_sample_rows <- function(chr, pos, sample_size = 1000L, min_distance = 1000L) {
    .Call(`_mclink_mc_sample_rows`, chr, pos, sample_size, min_distance)
}

simulate_panmixia <- function(data, iterations = 1000L, sample_size = 1000L, min_distance = 1000L) {
    .Call(`_mclink_simulate_panmixia`, data, iterations, sample_size, min_distance)
}

relative_diff <- function(M) {
    .Call(`_mclink_relative_diff`, M)
}

ld_decay_chr <- function(data, maf = 0.05, bin_size = 1000L, max_dist = 100000L) {
    .Call(`_mclink_ld_decay_chr`, data, maf, bin_size, max_dist)
}

