# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

relative_diff <- function(M) {
    .Call(`_mclink_relative_diff`, M)
}

shuffle_relative_diff <- function(M) {
    .Call(`_mclink_shuffle_relative_diff`, M)
}

cal_var <- function(M) {
    .Call(`_mclink_cal_var`, M)
}

nonzero <- function(M) {
    .Call(`_mclink_nonzero`, M)
}

